### ISSUE TITLE
Example project build issue

### ISSUE THREAD

**Issue by nareshtap** [GluuFederation/oxPush3#3]
Not able to build example project as files are missing
![missing files](https://user-images.githubusercontent.com/11648238/32277334-1bb78b48-bf38-11e7-9d1c-80b7405a43ad.png)
.

**Comment by nynymike** [comment]
Nazar, are all the requirement libraries listed ?

**Comment by NazarYavornytskyy** [comment]
Yea, all is fine with libs, need to check sources, going to check

**Comment by NazarYavornytskyy** [comment]
Please sync with latest changes and try again, Example should work now. If you notice something just let me know
